import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';

import { Injectable } from '@nestjs/common';

/**
 * How many random bytes back each token.
 *
 * 32 bytes is 256 bits of entropy — the same order as an AES key, and far
 * beyond anything brute-forceable. Base64url encoding makes it 43 URL-safe
 * characters, so it drops straight into a link without escaping.
 */
const TOKEN_BYTES = 32;

/**
 * Issues and checks the single-use tokens behind email verification and
 * password reset.
 *
 * Two rules govern everything here:
 *
 * **Tokens are generated by a CSPRNG, never derived.** A token built from a
 * timestamp, a counter, or a user id is predictable, and a predictable
 * verification token proves nothing about who controls the mailbox.
 * `randomBytes` draws from the operating system's cryptographic source.
 *
 * **We store a hash, never the token.** The plaintext exists exactly once,
 * inside the email we send. A database leak then yields no working links —
 * the same reasoning as passwords.
 *
 * Unlike passwords, the hash here is plain SHA-256 rather than argon2. That
 * is deliberate and worth understanding: argon2's cost exists to slow down
 * guessing of *low-entropy* secrets that humans chose. A 256-bit random
 * token has no guessable structure, so there is nothing to slow down —
 * argon2 would add latency to every verification click and buy nothing.
 * Matching the algorithm to the threat is the point, not reaching for the
 * strongest one available.
 */
@Injectable()
export class TokenService {
  /**
   * Mint a token.
   *
   * Returns both halves: `plaintext` goes in the email and is never
   * persisted, `hash` goes in the database and is never sent. Returning
   * them together makes it obvious at the call site which one is which.
   */
  public generate(): { plaintext: string; hash: string } {
    const plaintext = randomBytes(TOKEN_BYTES).toString('base64url');
    return { plaintext, hash: this.hash(plaintext) };
  }

  /** SHA-256, hex encoded. Used for storage and for lookup. */
  public hash(plaintext: string): string {
    return createHash('sha256').update(plaintext, 'utf8').digest('hex');
  }

  /**
   * Compare a presented token against a stored hash in constant time.
   *
   * A naive `===` on strings short-circuits at the first differing
   * character, so the time it takes leaks how many leading characters were
   * correct. Repeated across many attempts that is enough to reconstruct a
   * token one character at a time. `timingSafeEqual` always compares every
   * byte.
   *
   * In practice we look tokens up *by* hash, which is already constant-time
   * at the database level — but this exists for the paths that compare
   * directly, and because the cost of doing it correctly is nil.
   */
  public matches(plaintext: string, storedHash: string): boolean {
    const candidate = Buffer.from(this.hash(plaintext), 'hex');
    let stored: Buffer;

    try {
      stored = Buffer.from(storedHash, 'hex');
    } catch {
      return false;
    }

    // timingSafeEqual throws on length mismatch, which would itself leak
    // information. Check first and fail closed.
    if (candidate.length !== stored.length) return false;

    return timingSafeEqual(candidate, stored);
  }

  /** A timestamp `minutes` from now, for token expiry. */
  public expiryFromNow(minutes: number): Date {
    return new Date(Date.now() + minutes * 60_000);
  }
}
